project:
  type: Paolo Machaca-Beltran
  output-dir: docs

website:
  title: "Paolo Machaca-Beltran"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



